// export { default as core } from './core/router'
export { default as auth } from './auth/router'
export { default as user } from './user/router'
export { default as roadmap } from './roadmap/router'
export { default as credit } from './credit/router'
export { default as progress } from './progress/router'
export { default as admin } from './admin/interface/routes/router'
export { default as notification } from './notification/router'
export { default as share } from './share/router'
